api/urls.py
from django.urls import path
from rest_framework_simplejwt import views as jwt_views
from . import views


urlpatterns = [
    path('tasks/', views.TaskListCreateAPIView.as_view()),
    path('tasks/<int:pk>/', views.TaskRetrieveUpdateDestroyAPIView.as_view()),
    path('auth/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('auth/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
]

taskmanagement/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('tasks.urls')),
    # path('tasks/', include('tasks.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls'))
]

tasks/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='tasks'
urlpatterns = [
    path('', views.TaskListView.as_view(), name='all'),
    path('task/<int:pk>', views.TaskDetailView.as_view(), name='task_detail'),
    path('task/create',
        views.TaskCreateView.as_view(success_url=reverse_lazy('tasks:all')), name='task_create'),
    path('task/<int:pk>/update',
        views.TaskUpdateView.as_view(success_url=reverse_lazy('tasks:all')), name='task_update'),
    path('task/<int:pk>/delete',
        views.TaskDeleteView.as_view(success_url=reverse_lazy('tasks:all')), name='task_delete'),
]

api/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

tasks/models.py
from django.conf import settings
from django.db import models

class Task(models.Model):
    STATUS_CHOICES = (
        ('todo', 'ToDo'),
        ('in_progress', 'In Progress'),
        ('done', 'Done'),
    )
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='todo')
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    completed_at = models.DateTimeField(blank=True, null=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

tasks/forms.py
from django import forms
from tasks.models import Task


class TaskCreateForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description']

class TaskUpdateForm(forms.ModelForm):
    completed_at = forms.DateTimeInput()
    class Meta:
        model = Task
        fields = ['title', 'status', 'description', 'completed_at']

api/views.py
from api.serializers import TaskSerialzer
from tasks.models import Task
from rest_framework import generics, permissions
from django.db.models import Q

class TaskListCreateAPIView(generics.ListCreateAPIView):
    serializer_class = TaskSerialzer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]

    def get_queryset(self):
        query_set = Task.objects.all()
        if self.request.method not in permissions.SAFE_METHODS:
            query_set = Task.objects.filter(owner=self.request.user.id)
        search_value = self.request.query_params.get('search')
        if search_value:
            query = Q(title__icontains=search_value) 
            query.add(Q(description__icontains=search_value), Q.OR)
            query_set = Task.objects.filter(query).select_related()
        return query_set

class TaskRetrieveUpdateDestroyAPIView(generics.RetrieveUpdateDestroyAPIView):
    serializer_class = TaskSerialzer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
    def get_queryset(self):
        query_set = Task.objects.all()
        if self.request.method not in permissions.SAFE_METHODS:
            query_set = Task.objects.filter(owner=self.request.user.id)
        return query_set
    lookup_field = 'pk'

home/views.py
from django.shortcuts import render

# Create your views here.

tasks/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views import View
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import TaskCreateForm, TaskUpdateForm
from .models import Task
from .owner import OwnerListView, OwnerDetailView, OwnerUpdateView, OwnerDeleteView


class TaskListView(OwnerListView):
    model = Task
    template_name = "tasks/task_list.html"

    def get(self, request) :
        task_list = Task.objects.all()
        search_value =  request.GET.get("search", False)
        if search_value :
            query = Q(title__icontains=search_value) 
            query.add(Q(description__icontains=search_value), Q.OR)
            task_list = Task.objects.filter(query).select_related()
        else :
            task_list = Task.objects.all()
        ctx = {'task_list' : task_list, 'search': search_value}
        return render(request, self.template_name, ctx)


class TaskDetailView(OwnerDetailView):
    model = Task
    template_name = "tasks/task_detail.html"
    def get(self, request, pk) :
        task = Task.objects.get(id=pk)
        context = { 'task' : task }
        return render(request, self.template_name, context)

class TaskCreateView(LoginRequiredMixin, View):
    template_name = 'tasks/task_form.html'
    success_url = reverse_lazy('tasks:all')

    def get(self, request, pk=None):
        form = TaskCreateForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        form = TaskCreateForm(request.POST)
        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        inst = form.save(commit=False)
        inst.owner = self.request.user
        inst.save()
        return redirect(self.success_url)

class TaskUpdateView(LoginRequiredMixin, View):
    template_name = 'tasks/task_form.html'
    success_url = reverse_lazy('tasks:all')

    def get(self, request, pk):
        task = get_object_or_404(Task, id=pk, owner=self.request.user)
        form = TaskUpdateForm(instance=task)
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        inst = get_object_or_404(Task, id=pk, owner=self.request.user)
        form = TaskUpdateForm(request.POST, None, instance=inst)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        inst = form.save(commit=False)
        inst.owner = self.request.user
        inst.save()

        return redirect(self.success_url)


class TaskDeleteView(OwnerDeleteView):
    model = Task

home/templates/base_bootstrap.html
<!DOCTYPE html>
<html>
<head>
<title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap-theme.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
     crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"
    crossorigin="anonymous"></script>

<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

<meta name="dj4e-version" content="2022-09-01">

{% block head %} {% endblock %}

</head>
<body>
<div class="container">
{% block navbar %} {% endblock %}
{% block welcome %} {% endblock %}
{% block messages %}
    {% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{msg.message}}
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}
{% block content %}
{% endblock %}
</div>
{% block footer %} {% endblock %}
</body>
</html>

home/templates/base_menu.html
{% extends "base_bootstrap.html" %}
{% block navbar %}
<nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="/">{{ settings.APP_NAME }}</a>
    </div>
    <ul class="nav navbar-nav">
      {% url 'tasks' as tasks %}
      <li {% if request.get_full_path == tasks %}class="active"{% endif %}>
          <a href="{% url 'tasks:all' %}">Tasks</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li>
        <a href="{% url 'tasks:task_create' %}">Create Task</a>
        </li>
        <li class="dropdown">
            <ul class="dropdown-menu">
                <li><a href="{% url 'logout' %}?next={% url 'tasks:all' %}">Logout</a></li>
            </ul>
        </li>
        {% else %}
        <li>
        <a href="{% url 'login' %}?next={% url 'tasks:all' %}">Login</a>
        </li>
        {% endif %}
    </ul>
  </div>
</nav>
{% endblock %}

tasks/templates/base_bootstrap.html
<!DOCTYPE html>
<html>
<head>
<title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap-theme.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
     crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"
    crossorigin="anonymous"></script>

<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

<meta name="dj4e-version" content="2022-09-01">

{% block head %} {% endblock %}

</head>
<body>
<div class="container">
{% block navbar %} {% endblock %}
{% block welcome %} {% endblock %}
{% block messages %}
    {% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{msg.message}}
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}
{% block content %}
{% endblock %}
</div>
{% block footer %} {% endblock %}
</body>
</html>

tasks/templates/tasks/task_confirm_delete.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Delete Task</h1>

<p>Are you sure you want to delete the task: {{ task }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

tasks/templates/tasks/task_detail.html
{% extends "base_menu.html" %}
{% load humanize %}
{% block content %}
<span style="float: right;">
({{ task.created_at|naturaltime }})
{% if task.owner == user %}
<a href="{% url 'tasks:task_update' task.id %}"><i class="fa fa-pencil"></i></a>
<a href="{% url 'tasks:task_delete' task.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</span>
<h1>{{ task.title }}</h1>
<p>
{{ task.description }}
</p>
<p>
<a href="{% url 'tasks:all' %}">All tasks</a>
</p>
{% if user.is_authenticated %}
<br clear="all"/>
{% endif %}
{% endblock %}

tasks/templates/tasks/task_form.html
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}
{% block content %}
<p>
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'tasks:all' %}';return false;">
  </form>
</p>
{% endblock %}

tasks/templates/tasks/task_list.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Tasks</h1>
<form>
  <input type="text" placeholder="Search.." name="search"
  {% if search %} value="{{ search }}" {% endif %}
  >
  <button type="submit"><i class="fa fa-search"></i></button>
<a href="{% url 'tasks:all' %}"><i class="fa fa-undo"></i></a>
</form>
<p>
{% if task_list %}
<ul>
  {% for task in task_list %}
    <li>
        <a href="{% url 'tasks:task_detail'  task.id %}">{{ task.title }}</a>
        {% if task.owner == user %}
        (<a href="{% url 'tasks:task_update' task.id %}">Edit</a> |
        <a href="{% url 'tasks:task_delete' task.id %}">Delete</a>)
        {% endif %}
    </li>
  {% endfor %}
</ul>
{% else %}
  <p>There are no tasks in the database.</p>
{% endif %}
</p>
<p>
<a href="{% url 'tasks:task_create' %}">Add an task</a> |
{% if user.is_authenticated %}
<a href="{% url 'logout' %}?next={% url 'tasks:all' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}?next={% url 'tasks:all' %}">Login</a>
{% endif %}
</p>
{% endblock %}